-- ============================================
-- ENABLE ROW LEVEL SECURITY
-- ============================================

-- Core tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE questionnaires ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE security_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE failed_login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_queue ENABLE ROW LEVEL SECURITY;

-- Config tables - public read
ALTER TABLE config_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_occasions ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_order_statuses ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_capacity ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_refund_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_faq ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_samples ENABLE ROW LEVEL SECURITY;
ALTER TABLE config_settings ENABLE ROW LEVEL SECURITY;
